### PR TITLE
Described more naming conventions

### PR DESCRIPTION
**Pull request by antongulenko**

### CODE REVIEW

**Review by mwallschlaeger — CHANGES_REQUESTED** [review]
idk sample templates yet. and still after reading the descriptions its hard to understand. are they only available in subpipelines?

**Comment by antongulenko** [comment]
The description says "Many processing steps take sample templates as parameters". It's just a 'concept' for a template string. Check out the descriptions for the steps fork-template, output-files and set-tags, they use samples templates as parameters.
What could we write to make it more understandable?

**Comment by mwallschlaeger** [comment]
Ok i understood now. Maybe give a more clear example, like:
"if you want to output a file based on the name of a tag. Sample tags could be used like ..." 

I know its already in example but a small use-case text would help to understand it more easy

**Review by mwallschlaeger — DISMISSED** [review]

**Comment by kevinstyp** [comment]
LGTM

**Review by kevinstyp — APPROVED** [review]

**Pull request merged**
